FROM mcr.microsoft.com/playwright:v1.62.1-noble

WORKDIR /app

RUN apt-get update && apt-get install -y unzip \
    && rm -rf /var/lib/apt/lists/*

COPY --from=oven/bun:1.3.12 /usr/local/bin/bun /usr/local/bin/bun
RUN ln -s /usr/local/bin/bun /usr/local/bin/bunx
ENV PATH="/root/.bun/bin:$PATH"

COPY package.json bun.lock /app/

COPY frontend/package.json /app/frontend/
COPY packages/react-email/package.json /app/packages/react-email/

WORKDIR /app/frontend

RUN bun install --frozen-lockfile

COPY ./frontend /app/frontend
