// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * AcquisitionConnectionState
 */
export type AcquisitionConnectionState = 'stopped' | 'connecting' | 'connected' | 'reconnecting' | 'error';

/**
 * AcquisitionDesiredState
 */
export type AcquisitionDesiredState = 'stopped' | 'running';

/**
 * AcquisitionNodeInput
 */
export type AcquisitionNodeInput = {
    /**
     * Tag Id
     */
    tag_id: string;
    /**
     * Node Id
     */
    node_id: string;
    /**
     * Is Enabled
     */
    is_enabled?: boolean;
};

/**
 * AcquisitionNodePublic
 */
export type AcquisitionNodePublic = {
    /**
     * Tag Id
     */
    tag_id: string;
    /**
     * Node Id
     */
    node_id: string;
    /**
     * Is Enabled
     */
    is_enabled?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Task Id
     */
    task_id: string;
    /**
     * Tag Code
     */
    tag_code: string;
    /**
     * Tag Name
     */
    tag_name: string;
    /**
     * Unit
     */
    unit?: string | null;
};

/**
 * AcquisitionTaskCreate
 */
export type AcquisitionTaskCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Endpoint Url
     */
    endpoint_url: string;
    /**
     * Publishing Interval Ms
     */
    publishing_interval_ms?: number;
    /**
     * Batch Size
     */
    batch_size?: number;
    /**
     * Reconnect Delay Seconds
     */
    reconnect_delay_seconds?: number;
    /**
     * Max Reconnect Delay Seconds
     */
    max_reconnect_delay_seconds?: number;
    /**
     * Plant Id
     */
    plant_id: string;
    /**
     * Nodes
     */
    nodes: Array<AcquisitionNodeInput>;
};

/**
 * AcquisitionTaskPublic
 */
export type AcquisitionTaskPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Endpoint Url
     */
    endpoint_url: string;
    /**
     * Publishing Interval Ms
     */
    publishing_interval_ms?: number;
    /**
     * Batch Size
     */
    batch_size?: number;
    /**
     * Reconnect Delay Seconds
     */
    reconnect_delay_seconds?: number;
    /**
     * Max Reconnect Delay Seconds
     */
    max_reconnect_delay_seconds?: number;
    /**
     * Id
     */
    id: string;
    /**
     * Plant Id
     */
    plant_id: string;
    desired_state: AcquisitionDesiredState;
    connection_state: AcquisitionConnectionState;
    /**
     * Last Connected At
     */
    last_connected_at: string | null;
    /**
     * Last Disconnected At
     */
    last_disconnected_at: string | null;
    /**
     * Last Sample At
     */
    last_sample_at: string | null;
    /**
     * Worker Heartbeat At
     */
    worker_heartbeat_at: string | null;
    /**
     * Error Count
     */
    error_count: number;
    /**
     * Reconnect Count
     */
    reconnect_count: number;
    /**
     * Samples Received
     */
    samples_received: number;
    /**
     * Samples Written
     */
    samples_written: number;
    /**
     * Duplicate Count
     */
    duplicate_count: number;
    /**
     * Dropped Count
     */
    dropped_count: number;
    /**
     * Last Error
     */
    last_error: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Nodes
     */
    nodes?: Array<AcquisitionNodePublic>;
};

/**
 * AcquisitionTaskUpdate
 */
export type AcquisitionTaskUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Endpoint Url
     */
    endpoint_url?: string | null;
    /**
     * Publishing Interval Ms
     */
    publishing_interval_ms?: number | null;
    /**
     * Batch Size
     */
    batch_size?: number | null;
    /**
     * Reconnect Delay Seconds
     */
    reconnect_delay_seconds?: number | null;
    /**
     * Max Reconnect Delay Seconds
     */
    max_reconnect_delay_seconds?: number | null;
    /**
     * Nodes
     */
    nodes?: Array<AcquisitionNodeInput> | null;
};

/**
 * AcquisitionTasksPublic
 */
export type AcquisitionTasksPublic = {
    /**
     * Data
     */
    data: Array<AcquisitionTaskPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Answer
 */
export type Answer = {
    /**
     * Status
     */
    status: 'answered' | 'no_answer' | 'clarification';
    /**
     * Answer
     */
    answer: string;
    /**
     * Citation Ids
     */
    citation_ids?: Array<string>;
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Evidence
     */
    evidence: Array<Evidence>;
    /**
     * Model
     */
    model: string;
    /**
     * Retrieval Mode
     */
    retrieval_mode: string;
    /**
     * Prompt Tokens
     */
    prompt_tokens: number;
    /**
     * Completion Tokens
     */
    completion_tokens: number;
    /**
     * Duration Ms
     */
    duration_ms: number;
    /**
     * Generated At
     */
    generated_at: string;
};

/**
 * AssetStatus
 */
export type AssetStatus = 'active' | 'inactive';

/**
 * AssistantRun
 */
export type AssistantRun = {
    /**
     * Id
     */
    id?: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Plant Id
     */
    plant_id: string;
    /**
     * Question Sha256
     */
    question_sha256: string;
    /**
     * Status
     */
    status?: string;
    /**
     * Model
     */
    model: string;
    /**
     * Retrieval Mode
     */
    retrieval_mode?: string;
    /**
     * Prompt Tokens
     */
    prompt_tokens?: number;
    /**
     * Completion Tokens
     */
    completion_tokens?: number;
    /**
     * Duration Ms
     */
    duration_ms?: number;
    /**
     * Tool Names
     */
    tool_names?: Array<string>;
    /**
     * Evidence Ids
     */
    evidence_ids?: Array<string>;
    /**
     * Error Code
     */
    error_code?: string | null;
    /**
     * Created At
     */
    created_at?: string;
};

/**
 * Body_data-imports-preview_import
 */
export type Body_data_imports_preview_import = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * CapacityPublic
 */
export type CapacityPublic = {
    /**
     * Measured At
     */
    measured_at: string;
    /**
     * Database Bytes
     */
    database_bytes: number;
    /**
     * Sample Total Bytes
     */
    sample_total_bytes: number;
    /**
     * Sample Index Bytes
     */
    sample_index_bytes: number;
    /**
     * Estimated Live Rows
     */
    estimated_live_rows: number;
    /**
     * Last Analyze
     */
    last_analyze: string | null;
    /**
     * Estimated Bytes Per Row
     */
    estimated_bytes_per_row: number | null;
    /**
     * Planning Rows Per Second
     */
    planning_rows_per_second: number;
    /**
     * Estimated Daily Bytes
     */
    estimated_daily_bytes: number | null;
    /**
     * Host Free Bytes
     */
    host_free_bytes?: null;
    /**
     * Note
     */
    note: string;
};

/**
 * DashboardSummaryPublic
 */
export type DashboardSummaryPublic = {
    /**
     * Plant Count
     */
    plant_count: number;
    /**
     * Production Line Count
     */
    production_line_count: number;
    /**
     * Device Count
     */
    device_count: number;
    /**
     * Tag Count
     */
    tag_count: number;
    /**
     * Enabled Tag Count
     */
    enabled_tag_count: number;
    /**
     * Acquisition Task Count
     */
    acquisition_task_count: number;
    /**
     * Running Task Count
     */
    running_task_count: number;
    /**
     * Connected Task Count
     */
    connected_task_count: number;
    /**
     * Sample Count
     */
    sample_count: number;
    /**
     * Latest Sample At
     */
    latest_sample_at: string | null;
    /**
     * Import Batch Count
     */
    import_batch_count: number;
    /**
     * Completed Import Batch Count
     */
    completed_import_batch_count: number;
    /**
     * Quality Issue Count
     */
    quality_issue_count: number;
    /**
     * Generated At
     */
    generated_at: string;
};

/**
 * DataQualityIssuePublic
 */
export type DataQualityIssuePublic = {
    /**
     * Id
     */
    id: number;
    /**
     * Batch Id
     */
    batch_id: string;
    /**
     * Row Number
     */
    row_number: number;
    issue_type: DataQualityIssueType;
    severity: DataQualitySeverity;
    /**
     * Field Name
     */
    field_name: string | null;
    /**
     * Raw Value
     */
    raw_value: string | null;
    /**
     * Message
     */
    message: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * DataQualityIssueSummaryItem
 */
export type DataQualityIssueSummaryItem = {
    issue_type: DataQualityIssueType;
    severity: DataQualitySeverity;
    /**
     * Count
     */
    count: number;
};

/**
 * DataQualityIssueSummaryPublic
 */
export type DataQualityIssueSummaryPublic = {
    /**
     * Data
     */
    data: Array<DataQualityIssueSummaryItem>;
};

/**
 * DataQualityIssueType
 */
export type DataQualityIssueType = 'missing_required' | 'invalid_timestamp' | 'invalid_value' | 'out_of_range' | 'unknown_tag' | 'ambiguous_tag' | 'duplicate_in_file' | 'duplicate_existing' | 'bad_quality';

/**
 * DataQualityIssuesPublic
 */
export type DataQualityIssuesPublic = {
    /**
     * Data
     */
    data: Array<DataQualityIssuePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * DataQualitySeverity
 */
export type DataQualitySeverity = 'error' | 'warning';

/**
 * DeviceCreate
 */
export type DeviceCreate = {
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
    status?: AssetStatus;
    /**
     * Device Type
     */
    device_type: string;
    /**
     * Manufacturer
     */
    manufacturer?: string | null;
    /**
     * Model
     */
    model?: string | null;
    /**
     * Production Line Id
     */
    production_line_id: string;
};

/**
 * DevicePublic
 */
export type DevicePublic = {
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
    status?: AssetStatus;
    /**
     * Device Type
     */
    device_type: string;
    /**
     * Manufacturer
     */
    manufacturer?: string | null;
    /**
     * Model
     */
    model?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Production Line Id
     */
    production_line_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * DeviceUpdate
 */
export type DeviceUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Device Type
     */
    device_type?: string | null;
    /**
     * Manufacturer
     */
    manufacturer?: string | null;
    /**
     * Model
     */
    model?: string | null;
    status?: AssetStatus | null;
};

/**
 * DevicesPublic
 */
export type DevicesPublic = {
    /**
     * Data
     */
    data: Array<DevicePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * DocumentInput
 */
export type DocumentInput = {
    /**
     * Title
     */
    title: string;
    /**
     * Content
     */
    content: string;
    /**
     * Expected Version
     */
    expected_version?: number | null;
    /**
     * Allow External Processing
     */
    allow_external_processing?: boolean;
};

/**
 * DocumentPublic
 */
export type DocumentPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Plant Id
     */
    plant_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Version
     */
    version: number;
    /**
     * Content Sha256
     */
    content_sha256: string;
    /**
     * Embedding Model
     */
    embedding_model: string | null;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Content
     */
    content: string;
};

/**
 * Evidence
 */
export type Evidence = {
    /**
     * Id
     */
    id: string;
    /**
     * Kind
     */
    kind: 'document' | 'tool' | 'capability';
    /**
     * Title
     */
    title: string;
    /**
     * Data
     */
    data: {
        [key: string]: unknown;
    };
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ImportBatchPublic
 */
export type ImportBatchPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Plant Id
     */
    plant_id: string;
    /**
     * Created By Id
     */
    created_by_id: string;
    /**
     * Duplicate Of Id
     */
    duplicate_of_id: string | null;
    /**
     * Original Filename
     */
    original_filename: string;
    /**
     * Source File Available
     */
    source_file_available: boolean;
    file_format: ImportFileFormat;
    /**
     * Content Type
     */
    content_type: string | null;
    /**
     * File Size Bytes
     */
    file_size_bytes: number;
    /**
     * File Sha256
     */
    file_sha256: string;
    /**
     * File Encoding
     */
    file_encoding: string | null;
    /**
     * Sheet Name
     */
    sheet_name: string | null;
    /**
     * Mapping Config
     */
    mapping_config: {
        [key: string]: unknown;
    } | null;
    status: ImportBatchStatus;
    /**
     * Total Rows
     */
    total_rows: number;
    /**
     * Accepted Rows
     */
    accepted_rows: number;
    /**
     * Rejected Rows
     */
    rejected_rows: number;
    /**
     * Duplicate Rows
     */
    duplicate_rows: number;
    /**
     * Warning Rows
     */
    warning_rows: number;
    /**
     * Issue Count
     */
    issue_count: number;
    /**
     * Stored Issue Count
     */
    stored_issue_count: number;
    /**
     * Issues Truncated
     */
    issues_truncated: boolean;
    /**
     * Error Message
     */
    error_message: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Started At
     */
    started_at: string | null;
    /**
     * Completed At
     */
    completed_at: string | null;
};

/**
 * ImportBatchStatus
 */
export type ImportBatchStatus = 'uploaded' | 'queued' | 'duplicate' | 'processing' | 'completed' | 'failed';

/**
 * ImportBatchesPublic
 */
export type ImportBatchesPublic = {
    /**
     * Data
     */
    data: Array<ImportBatchPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ImportFileFormat
 */
export type ImportFileFormat = 'csv' | 'xlsx';

/**
 * ImportJobPublic
 */
export type ImportJobPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Batch Id
     */
    batch_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Attempts
     */
    attempts: number;
    /**
     * Processed Rows
     */
    processed_rows: number;
    /**
     * Attempt History
     */
    attempt_history: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Error Message
     */
    error_message: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Heartbeat At
     */
    heartbeat_at: string | null;
    /**
     * Completed At
     */
    completed_at: string | null;
};

/**
 * ImportLayout
 */
export type ImportLayout = 'long' | 'wide';

/**
 * ImportMappingInput
 */
export type ImportMappingInput = {
    layout?: ImportLayout;
    /**
     * Timestamp Column
     */
    timestamp_column: string;
    /**
     * Tag Code Column
     */
    tag_code_column?: string | null;
    /**
     * Value Column
     */
    value_column?: string | null;
    /**
     * Device Code Column
     */
    device_code_column?: string | null;
    /**
     * Quality Column
     */
    quality_column?: string | null;
    /**
     * Wide Columns
     */
    wide_columns?: Array<WideColumnMapping>;
};

/**
 * ImportPreviewPublic
 */
export type ImportPreviewPublic = {
    batch: ImportBatchPublic;
    /**
     * Source Columns
     */
    source_columns: Array<string>;
    /**
     * Preview Rows
     */
    preview_rows: Array<{
        [key: string]: unknown;
    }>;
    detected_layout: ImportLayout;
    /**
     * Suggested Timestamp Column
     */
    suggested_timestamp_column: string | null;
    suggested_mapping: ImportMappingInput | null;
};

/**
 * ImportTagOptionPublic
 */
export type ImportTagOptionPublic = {
    /**
     * Tag Id
     */
    tag_id: string;
    /**
     * Tag Code
     */
    tag_code: string;
    /**
     * Tag Name
     */
    tag_name: string;
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Device Code
     */
    device_code: string;
    /**
     * Device Name
     */
    device_name: string;
};

/**
 * LatestTagValuePublic
 */
export type LatestTagValuePublic = {
    /**
     * Node Id
     */
    node_id: string;
    /**
     * Tag Id
     */
    tag_id: string;
    /**
     * Tag Code
     */
    tag_code: string;
    /**
     * Tag Name
     */
    tag_name: string;
    data_type: TagDataType;
    /**
     * Unit
     */
    unit: string | null;
    /**
     * Sampling Interval Ms
     */
    sampling_interval_ms: number;
    /**
     * Sample Id
     */
    sample_id?: number | null;
    /**
     * Value
     */
    value?: unknown | null;
    /**
     * Numeric Value
     */
    numeric_value?: number | null;
    /**
     * Source Timestamp
     */
    source_timestamp?: string | null;
    /**
     * Server Timestamp
     */
    server_timestamp?: string | null;
    /**
     * Received At
     */
    received_at?: string | null;
    /**
     * Status Code
     */
    status_code?: string | null;
    /**
     * Is Good
     */
    is_good?: boolean | null;
};

/**
 * LatestTagValuesPublic
 */
export type LatestTagValuesPublic = {
    /**
     * Data
     */
    data: Array<LatestTagValuePublic>;
    /**
     * Count
     */
    count: number;
    /**
     * Generated At
     */
    generated_at: string;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * OpcUaBrowseNodePublic
 */
export type OpcUaBrowseNodePublic = {
    /**
     * Node Id
     */
    node_id: string;
    /**
     * Browse Name
     */
    browse_name: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Data Type
     */
    data_type?: string | null;
};

/**
 * OpcUaBrowseRequest
 */
export type OpcUaBrowseRequest = {
    /**
     * Plant Id
     */
    plant_id: string;
    /**
     * Endpoint Url
     */
    endpoint_url: string;
    /**
     * Root Node Id
     */
    root_node_id?: string;
    /**
     * Max Depth
     */
    max_depth?: number;
    /**
     * Max Nodes
     */
    max_nodes?: number;
};

/**
 * OpcUaBrowseResult
 */
export type OpcUaBrowseResult = {
    /**
     * Endpoint Url
     */
    endpoint_url: string;
    /**
     * Nodes
     */
    nodes: Array<OpcUaBrowseNodePublic>;
    /**
     * Truncated
     */
    truncated: boolean;
};

/**
 * PlantAccessPublic
 */
export type PlantAccessPublic = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Plant Ids
     */
    plant_ids: Array<string>;
};

/**
 * PlantAccessUpdate
 */
export type PlantAccessUpdate = {
    /**
     * Plant Ids
     */
    plant_ids: Array<string>;
};

/**
 * PlantCreate
 */
export type PlantCreate = {
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
    status?: AssetStatus;
    /**
     * Location
     */
    location?: string | null;
};

/**
 * PlantPublic
 */
export type PlantPublic = {
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
    status?: AssetStatus;
    /**
     * Location
     */
    location?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * PlantUpdate
 */
export type PlantUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Location
     */
    location?: string | null;
    status?: AssetStatus | null;
};

/**
 * PlantsPublic
 */
export type PlantsPublic = {
    /**
     * Data
     */
    data: Array<PlantPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * PreviewInput
 */
export type PreviewInput = {
    /**
     * Plant Id
     */
    plant_id: string;
    /**
     * Source Type
     */
    source_type: 'opcua' | 'file';
    /**
     * Keep Days
     */
    keep_days?: number;
};

/**
 * PreviewPublic
 */
export type PreviewPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Plant Id
     */
    plant_id: string;
    /**
     * Source Type
     */
    source_type: string;
    /**
     * Keep Days
     */
    keep_days: number;
    /**
     * Cutoff
     */
    cutoff: string;
    /**
     * High Water Id
     */
    high_water_id: number;
    /**
     * Matched Rows
     */
    matched_rows: number;
    /**
     * Count Is Exact
     */
    count_is_exact: boolean;
    /**
     * Scan Limit
     */
    scan_limit: number;
    /**
     * Affected Tags In Scan
     */
    affected_tags_in_scan: number;
    /**
     * Oldest In Scan
     */
    oldest_in_scan: string | null;
    /**
     * Newest In Scan
     */
    newest_in_scan: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Action Performed
     */
    action_performed?: 'preview_only';
    /**
     * Note
     */
    note?: string;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * ProductionLineCreate
 */
export type ProductionLineCreate = {
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
    status?: AssetStatus;
    /**
     * Process Type
     */
    process_type: string;
    /**
     * Plant Id
     */
    plant_id: string;
};

/**
 * ProductionLinePublic
 */
export type ProductionLinePublic = {
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
    status?: AssetStatus;
    /**
     * Process Type
     */
    process_type: string;
    /**
     * Id
     */
    id: string;
    /**
     * Plant Id
     */
    plant_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ProductionLineUpdate
 */
export type ProductionLineUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Process Type
     */
    process_type?: string | null;
    status?: AssetStatus | null;
};

/**
 * ProductionLinesPublic
 */
export type ProductionLinesPublic = {
    /**
     * Data
     */
    data: Array<ProductionLinePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Question
 */
export type Question = {
    /**
     * Plant Id
     */
    plant_id: string;
    /**
     * Question
     */
    question: string;
    /**
     * Allow External Processing
     */
    allow_external_processing?: boolean;
};

/**
 * SampleSourceType
 */
export type SampleSourceType = 'opcua' | 'file';

/**
 * ScenarioFrame
 */
export type ScenarioFrame = {
    /**
     * Elapsed Seconds
     */
    elapsed_seconds: number;
    /**
     * Timestamp
     */
    timestamp: string;
    /**
     * Phase
     */
    phase: string;
    /**
     * Values
     */
    values: {
        [key: string]: number;
    };
    /**
     * Bad Quality Codes
     */
    bad_quality_codes: Array<string>;
};

/**
 * ScenarioPoint
 */
export type ScenarioPoint = {
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
    /**
     * Line
     */
    line: number;
    /**
     * Device
     */
    device: string;
    /**
     * Unit
     */
    unit: string;
    /**
     * Minimum
     */
    minimum: number;
    /**
     * Maximum
     */
    maximum: number;
    /**
     * Baseline
     */
    baseline: number;
    /**
     * Purpose
     */
    purpose: string;
};

/**
 * TagCreate
 */
export type TagCreate = {
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
    data_type?: TagDataType;
    /**
     * Unit
     */
    unit?: string | null;
    /**
     * Min Value
     */
    min_value?: number | null;
    /**
     * Max Value
     */
    max_value?: number | null;
    /**
     * Sampling Interval Ms
     */
    sampling_interval_ms?: number;
    /**
     * Is Enabled
     */
    is_enabled?: boolean;
    /**
     * Device Id
     */
    device_id: string;
};

/**
 * TagDataType
 */
export type TagDataType = 'float' | 'integer' | 'boolean' | 'string';

/**
 * TagPublic
 */
export type TagPublic = {
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
    data_type?: TagDataType;
    /**
     * Unit
     */
    unit?: string | null;
    /**
     * Min Value
     */
    min_value?: number | null;
    /**
     * Max Value
     */
    max_value?: number | null;
    /**
     * Sampling Interval Ms
     */
    sampling_interval_ms?: number;
    /**
     * Is Enabled
     */
    is_enabled?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * TagSamplePublic
 */
export type TagSamplePublic = {
    /**
     * Id
     */
    id: number;
    /**
     * Task Id
     */
    task_id: string | null;
    /**
     * Import Batch Id
     */
    import_batch_id: string | null;
    source_type: SampleSourceType;
    /**
     * Tag Id
     */
    tag_id: string;
    /**
     * Value
     */
    value: unknown;
    /**
     * Numeric Value
     */
    numeric_value: number | null;
    /**
     * Source Timestamp
     */
    source_timestamp: string;
    /**
     * Server Timestamp
     */
    server_timestamp: string | null;
    /**
     * Received At
     */
    received_at: string;
    /**
     * Status Code
     */
    status_code: string;
    /**
     * Is Good
     */
    is_good: boolean;
};

/**
 * TagSamplesPublic
 */
export type TagSamplesPublic = {
    /**
     * Data
     */
    data: Array<TagSamplePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * TagUpdate
 */
export type TagUpdate = {
    /**
     * Name
     */
    name?: string | null;
    data_type?: TagDataType | null;
    /**
     * Unit
     */
    unit?: string | null;
    /**
     * Min Value
     */
    min_value?: number | null;
    /**
     * Max Value
     */
    max_value?: number | null;
    /**
     * Sampling Interval Ms
     */
    sampling_interval_ms?: number | null;
    /**
     * Is Enabled
     */
    is_enabled?: boolean | null;
};

/**
 * TagsPublic
 */
export type TagsPublic = {
    /**
     * Data
     */
    data: Array<TagPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * TeachingScenario
 */
export type TeachingScenario = {
    /**
     * Version
     */
    version: string;
    /**
     * Title
     */
    title: string;
    /**
     * Source
     */
    source: string;
    /**
     * Warning
     */
    warning: string;
    /**
     * Seed
     */
    seed: number;
    /**
     * Interval Seconds
     */
    interval_seconds: number;
    /**
     * Csv Sha256
     */
    csv_sha256: string;
    /**
     * Points
     */
    points: Array<ScenarioPoint>;
    /**
     * Frames
     */
    frames: Array<ScenarioFrame>;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    role?: UserRole;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    role?: UserRole;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserRole
 */
export type UserRole = 'admin' | 'engineer' | 'observer';

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    role?: UserRole | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * WideColumnMapping
 */
export type WideColumnMapping = {
    /**
     * Source Column
     */
    source_column: string;
    /**
     * Tag Code
     */
    tag_code: string;
    /**
     * Device Code
     */
    device_code?: string | null;
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type loginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type loginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordError = loginRecoverPasswordErrors[keyof loginRecoverPasswordErrors];

export type loginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginRecoverPasswordResponse = loginRecoverPasswordResponses[keyof loginRecoverPasswordResponses];

export type loginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type loginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginResetPasswordError = loginResetPasswordErrors[keyof loginResetPasswordErrors];

export type loginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginResetPasswordResponse = loginResetPasswordResponses[keyof loginResetPasswordResponses];

export type loginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type loginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordHtmlContentError = loginRecoverPasswordHtmlContentErrors[keyof loginRecoverPasswordHtmlContentErrors];

export type loginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type loginRecoverPasswordHtmlContentResponse = loginRecoverPasswordHtmlContentResponses[keyof loginRecoverPasswordHtmlContentResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type usersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersRegisterUserError = usersRegisterUserErrors[keyof usersRegisterUserErrors];

export type usersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersRegisterUserResponse = usersRegisterUserResponses[keyof usersRegisterUserResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type usersReadUserPlantAccessData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}/plant-access';
};

export type usersReadUserPlantAccessErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserPlantAccessError = usersReadUserPlantAccessErrors[keyof usersReadUserPlantAccessErrors];

export type usersReadUserPlantAccessResponses = {
    /**
     * Successful Response
     */
    200: PlantAccessPublic;
};

export type usersReadUserPlantAccessResponse = usersReadUserPlantAccessResponses[keyof usersReadUserPlantAccessResponses];

export type usersReplaceUserPlantAccessData = {
    body: PlantAccessUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}/plant-access';
};

export type usersReplaceUserPlantAccessErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReplaceUserPlantAccessError = usersReplaceUserPlantAccessErrors[keyof usersReplaceUserPlantAccessErrors];

export type usersReplaceUserPlantAccessResponses = {
    /**
     * Successful Response
     */
    200: PlantAccessPublic;
};

export type usersReplaceUserPlantAccessResponse = usersReplaceUserPlantAccessResponses[keyof usersReplaceUserPlantAccessResponses];

export type utilsBrowserTestSafetyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/browser-test-safety/';
};

export type utilsBrowserTestSafetyResponses = {
    /**
     * Response Utils-Browser Test Safety
     *
     * Successful Response
     */
    200: {
        [key: string]: boolean;
    };
};

export type utilsBrowserTestSafetyResponse = utilsBrowserTestSafetyResponses[keyof utilsBrowserTestSafetyResponses];

export type utilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type utilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type utilsTestEmailError = utilsTestEmailErrors[keyof utilsTestEmailErrors];

export type utilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type utilsTestEmailResponse = utilsTestEmailResponses[keyof utilsTestEmailResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type dashboardReadSummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/dashboard/summary';
};

export type dashboardReadSummaryResponses = {
    /**
     * Successful Response
     */
    200: DashboardSummaryPublic;
};

export type dashboardReadSummaryResponse = dashboardReadSummaryResponses[keyof dashboardReadSummaryResponses];

export type demoReadScenarioData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/demo/scenario';
};

export type demoReadScenarioResponses = {
    /**
     * Successful Response
     */
    200: TeachingScenario;
};

export type demoReadScenarioResponse = demoReadScenarioResponses[keyof demoReadScenarioResponses];

export type demoDownloadScenarioData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/demo/scenario.csv';
};

export type demoDownloadScenarioResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type dataLifecycleReadCapacityData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Planning Rows Per Second
         */
        planning_rows_per_second?: number;
    };
    url: '/api/v1/data-lifecycle/capacity';
};

export type dataLifecycleReadCapacityErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type dataLifecycleReadCapacityError = dataLifecycleReadCapacityErrors[keyof dataLifecycleReadCapacityErrors];

export type dataLifecycleReadCapacityResponses = {
    /**
     * Successful Response
     */
    200: CapacityPublic;
};

export type dataLifecycleReadCapacityResponse = dataLifecycleReadCapacityResponses[keyof dataLifecycleReadCapacityResponses];

export type dataLifecycleListRetentionPreviewsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Plant Id
         */
        plant_id: string;
    };
    url: '/api/v1/data-lifecycle/previews';
};

export type dataLifecycleListRetentionPreviewsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type dataLifecycleListRetentionPreviewsError = dataLifecycleListRetentionPreviewsErrors[keyof dataLifecycleListRetentionPreviewsErrors];

export type dataLifecycleListRetentionPreviewsResponses = {
    /**
     * Response Data-Lifecycle-List Retention Previews
     *
     * Successful Response
     */
    200: Array<PreviewPublic>;
};

export type dataLifecycleListRetentionPreviewsResponse = dataLifecycleListRetentionPreviewsResponses[keyof dataLifecycleListRetentionPreviewsResponses];

export type dataLifecycleCreateRetentionPreviewData = {
    body: PreviewInput;
    path?: never;
    query?: never;
    url: '/api/v1/data-lifecycle/previews';
};

export type dataLifecycleCreateRetentionPreviewErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type dataLifecycleCreateRetentionPreviewError = dataLifecycleCreateRetentionPreviewErrors[keyof dataLifecycleCreateRetentionPreviewErrors];

export type dataLifecycleCreateRetentionPreviewResponses = {
    /**
     * Successful Response
     */
    201: PreviewPublic;
};

export type dataLifecycleCreateRetentionPreviewResponse = dataLifecycleCreateRetentionPreviewResponses[keyof dataLifecycleCreateRetentionPreviewResponses];

export type dataLifecycleReadRetentionPreviewData = {
    body?: never;
    path: {
        /**
         * Preview Id
         */
        preview_id: string;
    };
    query?: never;
    url: '/api/v1/data-lifecycle/previews/{preview_id}';
};

export type dataLifecycleReadRetentionPreviewErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type dataLifecycleReadRetentionPreviewError = dataLifecycleReadRetentionPreviewErrors[keyof dataLifecycleReadRetentionPreviewErrors];

export type dataLifecycleReadRetentionPreviewResponses = {
    /**
     * Successful Response
     */
    200: PreviewPublic;
};

export type dataLifecycleReadRetentionPreviewResponse = dataLifecycleReadRetentionPreviewResponses[keyof dataLifecycleReadRetentionPreviewResponses];

export type plantsReadPlantsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Status
         */
        status?: AssetStatus | null;
        /**
         * Query
         */
        query?: string | null;
    };
    url: '/api/v1/plants/';
};

export type plantsReadPlantsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type plantsReadPlantsError = plantsReadPlantsErrors[keyof plantsReadPlantsErrors];

export type plantsReadPlantsResponses = {
    /**
     * Successful Response
     */
    200: PlantsPublic;
};

export type plantsReadPlantsResponse = plantsReadPlantsResponses[keyof plantsReadPlantsResponses];

export type plantsCreatePlantData = {
    body: PlantCreate;
    path?: never;
    query?: never;
    url: '/api/v1/plants/';
};

export type plantsCreatePlantErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type plantsCreatePlantError = plantsCreatePlantErrors[keyof plantsCreatePlantErrors];

export type plantsCreatePlantResponses = {
    /**
     * Successful Response
     */
    200: PlantPublic;
};

export type plantsCreatePlantResponse = plantsCreatePlantResponses[keyof plantsCreatePlantResponses];

export type plantsReadPlantData = {
    body?: never;
    path: {
        /**
         * Plant Id
         */
        plant_id: string;
    };
    query?: never;
    url: '/api/v1/plants/{plant_id}';
};

export type plantsReadPlantErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type plantsReadPlantError = plantsReadPlantErrors[keyof plantsReadPlantErrors];

export type plantsReadPlantResponses = {
    /**
     * Successful Response
     */
    200: PlantPublic;
};

export type plantsReadPlantResponse = plantsReadPlantResponses[keyof plantsReadPlantResponses];

export type plantsUpdatePlantData = {
    body: PlantUpdate;
    path: {
        /**
         * Plant Id
         */
        plant_id: string;
    };
    query?: never;
    url: '/api/v1/plants/{plant_id}';
};

export type plantsUpdatePlantErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type plantsUpdatePlantError = plantsUpdatePlantErrors[keyof plantsUpdatePlantErrors];

export type plantsUpdatePlantResponses = {
    /**
     * Successful Response
     */
    200: PlantPublic;
};

export type plantsUpdatePlantResponse = plantsUpdatePlantResponses[keyof plantsUpdatePlantResponses];

export type plantsDisablePlantData = {
    body?: never;
    path: {
        /**
         * Plant Id
         */
        plant_id: string;
    };
    query?: never;
    url: '/api/v1/plants/{plant_id}/disable';
};

export type plantsDisablePlantErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type plantsDisablePlantError = plantsDisablePlantErrors[keyof plantsDisablePlantErrors];

export type plantsDisablePlantResponses = {
    /**
     * Successful Response
     */
    200: PlantPublic;
};

export type plantsDisablePlantResponse = plantsDisablePlantResponses[keyof plantsDisablePlantResponses];

export type productionLinesReadProductionLinesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Plant Id
         */
        plant_id?: string | null;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Status
         */
        status?: AssetStatus | null;
        /**
         * Query
         */
        query?: string | null;
    };
    url: '/api/v1/production-lines/';
};

export type productionLinesReadProductionLinesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type productionLinesReadProductionLinesError = productionLinesReadProductionLinesErrors[keyof productionLinesReadProductionLinesErrors];

export type productionLinesReadProductionLinesResponses = {
    /**
     * Successful Response
     */
    200: ProductionLinesPublic;
};

export type productionLinesReadProductionLinesResponse = productionLinesReadProductionLinesResponses[keyof productionLinesReadProductionLinesResponses];

export type productionLinesCreateProductionLineData = {
    body: ProductionLineCreate;
    path?: never;
    query?: never;
    url: '/api/v1/production-lines/';
};

export type productionLinesCreateProductionLineErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type productionLinesCreateProductionLineError = productionLinesCreateProductionLineErrors[keyof productionLinesCreateProductionLineErrors];

export type productionLinesCreateProductionLineResponses = {
    /**
     * Successful Response
     */
    200: ProductionLinePublic;
};

export type productionLinesCreateProductionLineResponse = productionLinesCreateProductionLineResponses[keyof productionLinesCreateProductionLineResponses];

export type productionLinesReadProductionLineData = {
    body?: never;
    path: {
        /**
         * Production Line Id
         */
        production_line_id: string;
    };
    query?: never;
    url: '/api/v1/production-lines/{production_line_id}';
};

export type productionLinesReadProductionLineErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type productionLinesReadProductionLineError = productionLinesReadProductionLineErrors[keyof productionLinesReadProductionLineErrors];

export type productionLinesReadProductionLineResponses = {
    /**
     * Successful Response
     */
    200: ProductionLinePublic;
};

export type productionLinesReadProductionLineResponse = productionLinesReadProductionLineResponses[keyof productionLinesReadProductionLineResponses];

export type productionLinesUpdateProductionLineData = {
    body: ProductionLineUpdate;
    path: {
        /**
         * Production Line Id
         */
        production_line_id: string;
    };
    query?: never;
    url: '/api/v1/production-lines/{production_line_id}';
};

export type productionLinesUpdateProductionLineErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type productionLinesUpdateProductionLineError = productionLinesUpdateProductionLineErrors[keyof productionLinesUpdateProductionLineErrors];

export type productionLinesUpdateProductionLineResponses = {
    /**
     * Successful Response
     */
    200: ProductionLinePublic;
};

export type productionLinesUpdateProductionLineResponse = productionLinesUpdateProductionLineResponses[keyof productionLinesUpdateProductionLineResponses];

export type productionLinesDisableProductionLineData = {
    body?: never;
    path: {
        /**
         * Production Line Id
         */
        production_line_id: string;
    };
    query?: never;
    url: '/api/v1/production-lines/{production_line_id}/disable';
};

export type productionLinesDisableProductionLineErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type productionLinesDisableProductionLineError = productionLinesDisableProductionLineErrors[keyof productionLinesDisableProductionLineErrors];

export type productionLinesDisableProductionLineResponses = {
    /**
     * Successful Response
     */
    200: ProductionLinePublic;
};

export type productionLinesDisableProductionLineResponse = productionLinesDisableProductionLineResponses[keyof productionLinesDisableProductionLineResponses];

export type devicesReadDevicesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Production Line Id
         */
        production_line_id?: string | null;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Status
         */
        status?: AssetStatus | null;
        /**
         * Device Type
         */
        device_type?: string | null;
        /**
         * Query
         */
        query?: string | null;
    };
    url: '/api/v1/devices/';
};

export type devicesReadDevicesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type devicesReadDevicesError = devicesReadDevicesErrors[keyof devicesReadDevicesErrors];

export type devicesReadDevicesResponses = {
    /**
     * Successful Response
     */
    200: DevicesPublic;
};

export type devicesReadDevicesResponse = devicesReadDevicesResponses[keyof devicesReadDevicesResponses];

export type devicesCreateDeviceData = {
    body: DeviceCreate;
    path?: never;
    query?: never;
    url: '/api/v1/devices/';
};

export type devicesCreateDeviceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type devicesCreateDeviceError = devicesCreateDeviceErrors[keyof devicesCreateDeviceErrors];

export type devicesCreateDeviceResponses = {
    /**
     * Successful Response
     */
    200: DevicePublic;
};

export type devicesCreateDeviceResponse = devicesCreateDeviceResponses[keyof devicesCreateDeviceResponses];

export type devicesReadDeviceData = {
    body?: never;
    path: {
        /**
         * Device Id
         */
        device_id: string;
    };
    query?: never;
    url: '/api/v1/devices/{device_id}';
};

export type devicesReadDeviceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type devicesReadDeviceError = devicesReadDeviceErrors[keyof devicesReadDeviceErrors];

export type devicesReadDeviceResponses = {
    /**
     * Successful Response
     */
    200: DevicePublic;
};

export type devicesReadDeviceResponse = devicesReadDeviceResponses[keyof devicesReadDeviceResponses];

export type devicesUpdateDeviceData = {
    body: DeviceUpdate;
    path: {
        /**
         * Device Id
         */
        device_id: string;
    };
    query?: never;
    url: '/api/v1/devices/{device_id}';
};

export type devicesUpdateDeviceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type devicesUpdateDeviceError = devicesUpdateDeviceErrors[keyof devicesUpdateDeviceErrors];

export type devicesUpdateDeviceResponses = {
    /**
     * Successful Response
     */
    200: DevicePublic;
};

export type devicesUpdateDeviceResponse = devicesUpdateDeviceResponses[keyof devicesUpdateDeviceResponses];

export type devicesDisableDeviceData = {
    body?: never;
    path: {
        /**
         * Device Id
         */
        device_id: string;
    };
    query?: never;
    url: '/api/v1/devices/{device_id}/disable';
};

export type devicesDisableDeviceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type devicesDisableDeviceError = devicesDisableDeviceErrors[keyof devicesDisableDeviceErrors];

export type devicesDisableDeviceResponses = {
    /**
     * Successful Response
     */
    200: DevicePublic;
};

export type devicesDisableDeviceResponse = devicesDisableDeviceResponses[keyof devicesDisableDeviceResponses];

export type tagsReadTagsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Device Id
         */
        device_id?: string | null;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Is Enabled
         */
        is_enabled?: boolean | null;
        /**
         * Data Type
         */
        data_type?: TagDataType | null;
        /**
         * Query
         */
        query?: string | null;
    };
    url: '/api/v1/tags/';
};

export type tagsReadTagsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tagsReadTagsError = tagsReadTagsErrors[keyof tagsReadTagsErrors];

export type tagsReadTagsResponses = {
    /**
     * Successful Response
     */
    200: TagsPublic;
};

export type tagsReadTagsResponse = tagsReadTagsResponses[keyof tagsReadTagsResponses];

export type tagsCreateTagData = {
    body: TagCreate;
    path?: never;
    query?: never;
    url: '/api/v1/tags/';
};

export type tagsCreateTagErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tagsCreateTagError = tagsCreateTagErrors[keyof tagsCreateTagErrors];

export type tagsCreateTagResponses = {
    /**
     * Successful Response
     */
    200: TagPublic;
};

export type tagsCreateTagResponse = tagsCreateTagResponses[keyof tagsCreateTagResponses];

export type tagsReadTagData = {
    body?: never;
    path: {
        /**
         * Tag Id
         */
        tag_id: string;
    };
    query?: never;
    url: '/api/v1/tags/{tag_id}';
};

export type tagsReadTagErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tagsReadTagError = tagsReadTagErrors[keyof tagsReadTagErrors];

export type tagsReadTagResponses = {
    /**
     * Successful Response
     */
    200: TagPublic;
};

export type tagsReadTagResponse = tagsReadTagResponses[keyof tagsReadTagResponses];

export type tagsUpdateTagData = {
    body: TagUpdate;
    path: {
        /**
         * Tag Id
         */
        tag_id: string;
    };
    query?: never;
    url: '/api/v1/tags/{tag_id}';
};

export type tagsUpdateTagErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tagsUpdateTagError = tagsUpdateTagErrors[keyof tagsUpdateTagErrors];

export type tagsUpdateTagResponses = {
    /**
     * Successful Response
     */
    200: TagPublic;
};

export type tagsUpdateTagResponse = tagsUpdateTagResponses[keyof tagsUpdateTagResponses];

export type tagsDisableTagData = {
    body?: never;
    path: {
        /**
         * Tag Id
         */
        tag_id: string;
    };
    query?: never;
    url: '/api/v1/tags/{tag_id}/disable';
};

export type tagsDisableTagErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tagsDisableTagError = tagsDisableTagErrors[keyof tagsDisableTagErrors];

export type tagsDisableTagResponses = {
    /**
     * Successful Response
     */
    200: TagPublic;
};

export type tagsDisableTagResponse = tagsDisableTagResponses[keyof tagsDisableTagResponses];

export type acquisitionReadTasksData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Plant Id
         */
        plant_id?: string | null;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/acquisition/tasks';
};

export type acquisitionReadTasksErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type acquisitionReadTasksError = acquisitionReadTasksErrors[keyof acquisitionReadTasksErrors];

export type acquisitionReadTasksResponses = {
    /**
     * Successful Response
     */
    200: AcquisitionTasksPublic;
};

export type acquisitionReadTasksResponse = acquisitionReadTasksResponses[keyof acquisitionReadTasksResponses];

export type acquisitionCreateTaskData = {
    body: AcquisitionTaskCreate;
    path?: never;
    query?: never;
    url: '/api/v1/acquisition/tasks';
};

export type acquisitionCreateTaskErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type acquisitionCreateTaskError = acquisitionCreateTaskErrors[keyof acquisitionCreateTaskErrors];

export type acquisitionCreateTaskResponses = {
    /**
     * Successful Response
     */
    200: AcquisitionTaskPublic;
};

export type acquisitionCreateTaskResponse = acquisitionCreateTaskResponses[keyof acquisitionCreateTaskResponses];

export type acquisitionReadTaskData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/acquisition/tasks/{task_id}';
};

export type acquisitionReadTaskErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type acquisitionReadTaskError = acquisitionReadTaskErrors[keyof acquisitionReadTaskErrors];

export type acquisitionReadTaskResponses = {
    /**
     * Successful Response
     */
    200: AcquisitionTaskPublic;
};

export type acquisitionReadTaskResponse = acquisitionReadTaskResponses[keyof acquisitionReadTaskResponses];

export type acquisitionUpdateTaskData = {
    body: AcquisitionTaskUpdate;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/acquisition/tasks/{task_id}';
};

export type acquisitionUpdateTaskErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type acquisitionUpdateTaskError = acquisitionUpdateTaskErrors[keyof acquisitionUpdateTaskErrors];

export type acquisitionUpdateTaskResponses = {
    /**
     * Successful Response
     */
    200: AcquisitionTaskPublic;
};

export type acquisitionUpdateTaskResponse = acquisitionUpdateTaskResponses[keyof acquisitionUpdateTaskResponses];

export type acquisitionStartTaskData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/acquisition/tasks/{task_id}/start';
};

export type acquisitionStartTaskErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type acquisitionStartTaskError = acquisitionStartTaskErrors[keyof acquisitionStartTaskErrors];

export type acquisitionStartTaskResponses = {
    /**
     * Successful Response
     */
    200: AcquisitionTaskPublic;
};

export type acquisitionStartTaskResponse = acquisitionStartTaskResponses[keyof acquisitionStartTaskResponses];

export type acquisitionStopTaskData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/acquisition/tasks/{task_id}/stop';
};

export type acquisitionStopTaskErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type acquisitionStopTaskError = acquisitionStopTaskErrors[keyof acquisitionStopTaskErrors];

export type acquisitionStopTaskResponses = {
    /**
     * Successful Response
     */
    200: AcquisitionTaskPublic;
};

export type acquisitionStopTaskResponse = acquisitionStopTaskResponses[keyof acquisitionStopTaskResponses];

export type acquisitionBrowseEndpointData = {
    body: OpcUaBrowseRequest;
    path?: never;
    query?: never;
    url: '/api/v1/acquisition/browse';
};

export type acquisitionBrowseEndpointErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type acquisitionBrowseEndpointError = acquisitionBrowseEndpointErrors[keyof acquisitionBrowseEndpointErrors];

export type acquisitionBrowseEndpointResponses = {
    /**
     * Successful Response
     */
    200: OpcUaBrowseResult;
};

export type acquisitionBrowseEndpointResponse = acquisitionBrowseEndpointResponses[keyof acquisitionBrowseEndpointResponses];

export type acquisitionReadTagSamplesData = {
    body?: never;
    path: {
        /**
         * Tag Id
         */
        tag_id: string;
    };
    query?: {
        /**
         * Task Id
         */
        task_id?: string | null;
        /**
         * Start
         */
        start?: string | null;
        /**
         * End
         */
        end?: string | null;
        /**
         * Is Good
         */
        is_good?: boolean | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/acquisition/tags/{tag_id}/samples';
};

export type acquisitionReadTagSamplesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type acquisitionReadTagSamplesError = acquisitionReadTagSamplesErrors[keyof acquisitionReadTagSamplesErrors];

export type acquisitionReadTagSamplesResponses = {
    /**
     * Successful Response
     */
    200: TagSamplesPublic;
};

export type acquisitionReadTagSamplesResponse = acquisitionReadTagSamplesResponses[keyof acquisitionReadTagSamplesResponses];

export type acquisitionReadLatestTaskValuesData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/acquisition/tasks/{task_id}/latest-values';
};

export type acquisitionReadLatestTaskValuesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type acquisitionReadLatestTaskValuesError = acquisitionReadLatestTaskValuesErrors[keyof acquisitionReadLatestTaskValuesErrors];

export type acquisitionReadLatestTaskValuesResponses = {
    /**
     * Successful Response
     */
    200: LatestTagValuesPublic;
};

export type acquisitionReadLatestTaskValuesResponse = acquisitionReadLatestTaskValuesResponses[keyof acquisitionReadLatestTaskValuesResponses];

export type dataImportsPreviewImportData = {
    body: Body_data_imports_preview_import;
    path?: never;
    query: {
        /**
         * Plant Id
         */
        plant_id: string;
    };
    url: '/api/v1/imports/preview';
};

export type dataImportsPreviewImportErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type dataImportsPreviewImportError = dataImportsPreviewImportErrors[keyof dataImportsPreviewImportErrors];

export type dataImportsPreviewImportResponses = {
    /**
     * Successful Response
     */
    200: ImportPreviewPublic;
};

export type dataImportsPreviewImportResponse = dataImportsPreviewImportResponses[keyof dataImportsPreviewImportResponses];

export type dataImportsProcessImportData = {
    body: ImportMappingInput;
    path: {
        /**
         * Batch Id
         */
        batch_id: string;
    };
    query?: never;
    url: '/api/v1/imports/{batch_id}/process';
};

export type dataImportsProcessImportErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type dataImportsProcessImportError = dataImportsProcessImportErrors[keyof dataImportsProcessImportErrors];

export type dataImportsProcessImportResponses = {
    /**
     * Successful Response
     */
    202: ImportBatchPublic;
};

export type dataImportsProcessImportResponse = dataImportsProcessImportResponses[keyof dataImportsProcessImportResponses];

export type dataImportsReadImportJobData = {
    body?: never;
    path: {
        /**
         * Batch Id
         */
        batch_id: string;
    };
    query?: never;
    url: '/api/v1/imports/{batch_id}/job';
};

export type dataImportsReadImportJobErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type dataImportsReadImportJobError = dataImportsReadImportJobErrors[keyof dataImportsReadImportJobErrors];

export type dataImportsReadImportJobResponses = {
    /**
     * Response Data-Imports-Read Import Job
     *
     * Successful Response
     */
    200: ImportJobPublic | null;
};

export type dataImportsReadImportJobResponse = dataImportsReadImportJobResponses[keyof dataImportsReadImportJobResponses];

export type dataImportsReadImportBatchesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Plant Id
         */
        plant_id?: string | null;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/imports';
};

export type dataImportsReadImportBatchesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type dataImportsReadImportBatchesError = dataImportsReadImportBatchesErrors[keyof dataImportsReadImportBatchesErrors];

export type dataImportsReadImportBatchesResponses = {
    /**
     * Successful Response
     */
    200: ImportBatchesPublic;
};

export type dataImportsReadImportBatchesResponse = dataImportsReadImportBatchesResponses[keyof dataImportsReadImportBatchesResponses];

export type dataImportsReadMappingOptionsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Plant Id
         */
        plant_id: string;
    };
    url: '/api/v1/imports/mapping-options';
};

export type dataImportsReadMappingOptionsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type dataImportsReadMappingOptionsError = dataImportsReadMappingOptionsErrors[keyof dataImportsReadMappingOptionsErrors];

export type dataImportsReadMappingOptionsResponses = {
    /**
     * Response Data-Imports-Read Mapping Options
     *
     * Successful Response
     */
    200: Array<ImportTagOptionPublic>;
};

export type dataImportsReadMappingOptionsResponse = dataImportsReadMappingOptionsResponses[keyof dataImportsReadMappingOptionsResponses];

export type dataImportsReadImportBatchData = {
    body?: never;
    path: {
        /**
         * Batch Id
         */
        batch_id: string;
    };
    query?: never;
    url: '/api/v1/imports/{batch_id}';
};

export type dataImportsReadImportBatchErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type dataImportsReadImportBatchError = dataImportsReadImportBatchErrors[keyof dataImportsReadImportBatchErrors];

export type dataImportsReadImportBatchResponses = {
    /**
     * Successful Response
     */
    200: ImportBatchPublic;
};

export type dataImportsReadImportBatchResponse = dataImportsReadImportBatchResponses[keyof dataImportsReadImportBatchResponses];

export type dataImportsReadQualityIssuesData = {
    body?: never;
    path: {
        /**
         * Batch Id
         */
        batch_id: string;
    };
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/imports/{batch_id}/issues';
};

export type dataImportsReadQualityIssuesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type dataImportsReadQualityIssuesError = dataImportsReadQualityIssuesErrors[keyof dataImportsReadQualityIssuesErrors];

export type dataImportsReadQualityIssuesResponses = {
    /**
     * Successful Response
     */
    200: DataQualityIssuesPublic;
};

export type dataImportsReadQualityIssuesResponse = dataImportsReadQualityIssuesResponses[keyof dataImportsReadQualityIssuesResponses];

export type dataImportsReadQualityIssueSummaryData = {
    body?: never;
    path: {
        /**
         * Batch Id
         */
        batch_id: string;
    };
    query?: never;
    url: '/api/v1/imports/{batch_id}/issue-summary';
};

export type dataImportsReadQualityIssueSummaryErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type dataImportsReadQualityIssueSummaryError = dataImportsReadQualityIssueSummaryErrors[keyof dataImportsReadQualityIssueSummaryErrors];

export type dataImportsReadQualityIssueSummaryResponses = {
    /**
     * Successful Response
     */
    200: DataQualityIssueSummaryPublic;
};

export type dataImportsReadQualityIssueSummaryResponse = dataImportsReadQualityIssueSummaryResponses[keyof dataImportsReadQualityIssueSummaryResponses];

export type dataImportsDownloadQualityIssuesData = {
    body?: never;
    path: {
        /**
         * Batch Id
         */
        batch_id: string;
    };
    query?: never;
    url: '/api/v1/imports/{batch_id}/issues.csv';
};

export type dataImportsDownloadQualityIssuesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type dataImportsDownloadQualityIssuesError = dataImportsDownloadQualityIssuesErrors[keyof dataImportsDownloadQualityIssuesErrors];

export type dataImportsDownloadQualityIssuesResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type dataImportsDeleteSourceFileData = {
    body?: never;
    path: {
        /**
         * Batch Id
         */
        batch_id: string;
    };
    query?: never;
    url: '/api/v1/imports/{batch_id}/source-file';
};

export type dataImportsDeleteSourceFileErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type dataImportsDeleteSourceFileError = dataImportsDeleteSourceFileErrors[keyof dataImportsDeleteSourceFileErrors];

export type dataImportsDeleteSourceFileResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type dataImportsDeleteSourceFileResponse = dataImportsDeleteSourceFileResponses[keyof dataImportsDeleteSourceFileResponses];

export type aiAssistantAssistantStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/assistant/status';
};

export type aiAssistantAssistantStatusResponses = {
    /**
     * Response Ai-Assistant-Assistant Status
     *
     * Successful Response
     */
    200: {
        [key: string]: string | boolean | number;
    };
};

export type aiAssistantAssistantStatusResponse = aiAssistantAssistantStatusResponses[keyof aiAssistantAssistantStatusResponses];

export type aiAssistantAskData = {
    body: Question;
    path?: never;
    query?: never;
    url: '/api/v1/assistant/ask';
};

export type aiAssistantAskErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type aiAssistantAskError = aiAssistantAskErrors[keyof aiAssistantAskErrors];

export type aiAssistantAskResponses = {
    /**
     * Successful Response
     */
    200: Answer;
};

export type aiAssistantAskResponse = aiAssistantAskResponses[keyof aiAssistantAskResponses];

export type aiAssistantListDocumentsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Plant Id
         */
        plant_id: string;
    };
    url: '/api/v1/assistant/documents';
};

export type aiAssistantListDocumentsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type aiAssistantListDocumentsError = aiAssistantListDocumentsErrors[keyof aiAssistantListDocumentsErrors];

export type aiAssistantListDocumentsResponses = {
    /**
     * Response Ai-Assistant-List Documents
     *
     * Successful Response
     */
    200: Array<DocumentPublic>;
};

export type aiAssistantListDocumentsResponse = aiAssistantListDocumentsResponses[keyof aiAssistantListDocumentsResponses];

export type aiAssistantCreateDocumentData = {
    body: DocumentInput;
    path?: never;
    query: {
        /**
         * Plant Id
         */
        plant_id: string;
    };
    url: '/api/v1/assistant/documents';
};

export type aiAssistantCreateDocumentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type aiAssistantCreateDocumentError = aiAssistantCreateDocumentErrors[keyof aiAssistantCreateDocumentErrors];

export type aiAssistantCreateDocumentResponses = {
    /**
     * Successful Response
     */
    200: DocumentPublic;
};

export type aiAssistantCreateDocumentResponse = aiAssistantCreateDocumentResponses[keyof aiAssistantCreateDocumentResponses];

export type aiAssistantDeleteDocumentData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query: {
        /**
         * Plant Id
         */
        plant_id: string;
        /**
         * Expected Version
         */
        expected_version: number;
    };
    url: '/api/v1/assistant/documents/{document_id}';
};

export type aiAssistantDeleteDocumentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type aiAssistantDeleteDocumentError = aiAssistantDeleteDocumentErrors[keyof aiAssistantDeleteDocumentErrors];

export type aiAssistantDeleteDocumentResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type aiAssistantDeleteDocumentResponse = aiAssistantDeleteDocumentResponses[keyof aiAssistantDeleteDocumentResponses];

export type aiAssistantUpdateDocumentData = {
    body: DocumentInput;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query: {
        /**
         * Plant Id
         */
        plant_id: string;
    };
    url: '/api/v1/assistant/documents/{document_id}';
};

export type aiAssistantUpdateDocumentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type aiAssistantUpdateDocumentError = aiAssistantUpdateDocumentErrors[keyof aiAssistantUpdateDocumentErrors];

export type aiAssistantUpdateDocumentResponses = {
    /**
     * Successful Response
     */
    200: DocumentPublic;
};

export type aiAssistantUpdateDocumentResponse = aiAssistantUpdateDocumentResponses[keyof aiAssistantUpdateDocumentResponses];

export type aiAssistantSearchDocumentsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Plant Id
         */
        plant_id: string;
        /**
         * Query
         */
        query: string;
    };
    url: '/api/v1/assistant/search';
};

export type aiAssistantSearchDocumentsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type aiAssistantSearchDocumentsError = aiAssistantSearchDocumentsErrors[keyof aiAssistantSearchDocumentsErrors];

export type aiAssistantSearchDocumentsResponses = {
    /**
     * Response Ai-Assistant-Search Documents
     *
     * Successful Response
     */
    200: Array<Evidence>;
};

export type aiAssistantSearchDocumentsResponse = aiAssistantSearchDocumentsResponses[keyof aiAssistantSearchDocumentsResponses];

export type aiAssistantReadRunsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Plant Id
         */
        plant_id: string;
    };
    url: '/api/v1/assistant/runs';
};

export type aiAssistantReadRunsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type aiAssistantReadRunsError = aiAssistantReadRunsErrors[keyof aiAssistantReadRunsErrors];

export type aiAssistantReadRunsResponses = {
    /**
     * Response Ai-Assistant-Read Runs
     *
     * Successful Response
     */
    200: Array<AssistantRun>;
};

export type aiAssistantReadRunsResponse = aiAssistantReadRunsResponses[keyof aiAssistantReadRunsResponses];

export type privateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type privateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type privateCreateUserError = privateCreateUserErrors[keyof privateCreateUserErrors];

export type privateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type privateCreateUserResponse = privateCreateUserResponses[keyof privateCreateUserResponses];
